export const CATAGORIES_ACTION_TYPES = {
  SET_CATAGORIES_ARRAY: "categories/SET_CATEGORIES_STARTY",
  FETCH_CATAGORIES_SUCCESS: "categories/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATAGORIES_FAILED: "categories/FETCH_CATEGORIES_FAILED",
};
